import Head from 'next/head';
import LandingContent from "../components/LandingContent";
import Layout from "../components/Layout";

export default function Home() {

  return (
    <>
      <Head>
        <title>Home - Who wants to be a sultan?</title>
        <meta name="description" content="Generated by create-wc-dapp" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout>
        <LandingContent />
      </Layout >
    </>
  );
}