import React from "react";
import Layout from "../components/Layout";
import Head from "next/head";
import RaffleContent from "@/components/RaffleContent";
import AdminPanel from "@/components/AdminPanel";

const raffle = () => {
  return (
    <>
      <Head>
        <title>Raffle - Who wants to be a sultan?</title>
        <meta name="description" content="Generated by create-wc-dapp" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout>
        <RaffleContent />
      </Layout>

      <AdminPanel />
    </>
  );
};

export default raffle;
